name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Download config file
        run: |
          curl -o config.toml "${{ secrets.CONFIG_FILE_URL }}"
          echo "Config file downloaded successfully"
          ls -la config.toml

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.4
        timeout-minutes: 5
        with:
          stack: dual
          mode: wireguard
          
      - name: Run Docker container
        run: |
          docker run --rm -q \
            -v "$(pwd)/config.toml:/app/config.toml:ro" \
            ${{ secrets.DOCKER_IMAGE }} \
            ${{ secrets.DOCKER_COMMAND }}
